spring:
  application:
    name: commerce-api
  datasource:
    url: jdbc:mysql://localhost:3307/commerce?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: commerce
    password: commerce
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      minimum-expected-value:
        http.server.requests: 5ms
      maximum-expected-value:
        http.server.requests: 10s

pg:
  api:
    base-url: http://www.pg.test
    private-key: pgtestprivatekey


jwt:
  secret: local-jwt-secret-key-example-32chars!!
  access-token-expiration-millis: 6000000
