spring:
  application:
    name: commerce-api
  jpa:
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-millis: ${JWT_ACCESS_TOKEN_EXPIRATION_MILLIS}

pg:
  api:
    base-url: ${PG_API_BASE_URL}
    private-key: ${PG_API_PRIVATE_KEY}
