server:
  port: ${SERVER_PORT}

spring:
  application:
    name: commerce-api
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      minimum-expected-value:
        http.server.requests: 5ms
      maximum-expected-value:
        http.server.requests: 10s

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-millis: ${JWT_ACCESS_TOKEN_EXPIRATION_MILLIS}

pg:
  api:
    base-url: ${PG_API_BASE_URL}
    private-key: ${PG_API_PRIVATE_KEY}
